In [118]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [119]:
corpus = "2022" 
metric = "var"
k = 10

full_corpus_name = {
    "2020": "misinfo-2020",
    "2021": "C4-2021",
    "2022": "C4-2022",
    "CLEF": "CLEF",
    "clef": "CLEF",
    "CLEF_v2": "CLEF_v2",
    "clef_v2": "CLEF_v2"
}

fields = {
    '2020': 'title',
    '2021': 'query',
    '2022': 'query',
    'CLEF': 'title',
    'clef': 'title',
    "CLEF_v2": "title",
    "clef_v2": "title"
}

In [120]:
scores = pd.read_csv(f"pre_qpp/{full_corpus_name[corpus]}_{metric}_{fields[corpus]}.csv", index_col=0)
scores

        sigma_1    sigma_2    sigma_3
151  116.101817  19.350303  35.501125
152   49.981538  24.990769  43.825776
153   47.679410  15.893137  23.780222
154   68.992798  22.997599  29.555744
155   62.268474  31.134237  34.403428
156   49.265697  16.421899  39.118725
157   23.072107  11.536054  11.787952
158   24.312253  12.156127  23.753450
159   61.565769  20.521923  40.403816
160    0.000000   0.000000   0.000000
161  147.981568  36.995392  62.444269
162   32.850402  16.425201  32.850402
163   63.793434  21.264478  39.530503
164   73.632597  18.408149  29.600375
165    1.328363   0.664181   1.328363
166  180.678189  22.584774  60.580046
167  170.887078  34.177416  57.826924
168   22.587883  11.293941  18.498431
169   27.426438  13.713219  17.971299
170   79.540972  26.513657  40.072401
171   93.479141  31.159714  54.099785
172   95.009135  31.669712  35.905929
173   17.291357   5.763786   9.834555
174  138.252059  46.084020  52.728486
175   81.778000  40.889000  69.275999
176   19.999611   9.999806  13.084075
177  101.082571  33.694190  43.775979
178   98.635191  32.878397  42.140372
179  145.403339  36.350835  48.164995
180  140.165858  35.041465  62.370271
181   23.426462  11.713231  16.794487
182   80.597630  26.865877  47.114516
183   60.506152  20.168717  41.565600
184   59.031597  11.806319  25.766180
185   82.207983  20.551996  51.243732
186  155.949402  38.987350  71.213249
187   86.862357  21.715589  42.908058
188   94.208829  31.402943  48.164995
189  137.558620  34.389655  47.114516
190   45.889220  11.472305  17.042179
191   73.070607  24.356869  48.855489
192   42.337686  14.112562  23.622801
193   83.707895  20.926974  48.661593
194   12.220484   4.073495  12.220484
195   47.067652  15.689217  36.054436
196   52.844273  26.422137  31.124686
197    8.974230   4.487115   8.974230
198  123.401418  24.680284  48.164995
199   39.941432  19.970716  20.782544
200   89.079314  22.269828  41.605078

In [121]:
scores.describe()

          sigma_1    sigma_2    sigma_3
count   50.000000  50.000000  50.000000
mean    72.678526  21.732731  36.064151
std     46.043639  10.819180  17.416743
min      0.000000   0.000000   0.000000
25%     40.540496  13.813055  23.655463
50%     66.393116  21.095726  39.324614
75%     94.809058  31.153345  48.164995
max    180.678189  46.084020  71.213249

In [122]:
if metric != "var":
    scores = scores.sort_values(by=metric, ascending=False)

In [123]:
df = scores.reset_index(names="topic")
df

    topic     sigma_1    sigma_2    sigma_3
0     151  116.101817  19.350303  35.501125
1     152   49.981538  24.990769  43.825776
2     153   47.679410  15.893137  23.780222
3     154   68.992798  22.997599  29.555744
4     155   62.268474  31.134237  34.403428
5     156   49.265697  16.421899  39.118725
6     157   23.072107  11.536054  11.787952
7     158   24.312253  12.156127  23.753450
8     159   61.565769  20.521923  40.403816
9     160    0.000000   0.000000   0.000000
10    161  147.981568  36.995392  62.444269
11    162   32.850402  16.425201  32.850402
12    163   63.793434  21.264478  39.530503
13    164   73.632597  18.408149  29.600375
14    165    1.328363   0.664181   1.328363
15    166  180.678189  22.584774  60.580046
16    167  170.887078  34.177416  57.826924
17    168   22.587883  11.293941  18.498431
18    169   27.426438  13.713219  17.971299
19    170   79.540972  26.513657  40.072401
20    171   93.479141  31.159714  54.099785
21    172   95.009135  31.669712  35.905929
22    173   17.291357   5.763786   9.834555
23    174  138.252059  46.084020  52.728486
24    175   81.778000  40.889000  69.275999
25    176   19.999611   9.999806  13.084075
26    177  101.082571  33.694190  43.775979
27    178   98.635191  32.878397  42.140372
28    179  145.403339  36.350835  48.164995
29    180  140.165858  35.041465  62.370271
30    181   23.426462  11.713231  16.794487
31    182   80.597630  26.865877  47.114516
32    183   60.506152  20.168717  41.565600
33    184   59.031597  11.806319  25.766180
34    185   82.207983  20.551996  51.243732
35    186  155.949402  38.987350  71.213249
36    187   86.862357  21.715589  42.908058
37    188   94.208829  31.402943  48.164995
38    189  137.558620  34.389655  47.114516
39    190   45.889220  11.472305  17.042179
40    191   73.070607  24.356869  48.855489
41    192   42.337686  14.112562  23.622801
42    193   83.707895  20.926974  48.661593
43    194   12.220484   4.073495  12.220484
44    195   47.067652  15.689217  36.054436
45    196   52.844273  26.422137  31.124686
46    197    8.974230   4.487115   8.974230
47    198  123.401418  24.680284  48.164995
48    199   39.941432  19.970716  20.782544
49    200   89.079314  22.269828  41.605078

In [124]:
if metric != "var":
    plt.figure(figsize=(8, 5))
    sns.histplot(df[metric], kde=True)
    plt.xlabel(f"{metric} - {corpus}", fontsize=14)
    plt.ylabel("Frecuencia")
    plt.title(f"Suma de scores de controversia - temps - {corpus}", fontsize=18, pad=15)
    plt.grid(True, alpha=0.5)

    plt.show()

In [125]:
# harmful_at_k_2020 = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_2020_bm25.csv')
# harmful_at_k_2021 = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_2021_bm25.csv')
# harmful_at_k_2022 = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_2022_bm25.csv')
# harmful_at_k_clef = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_clef_bm25.csv')
# harmful_at_k_clef_v2 = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_clef_v2_bm25.csv')

harmful_at_k_2020 = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_2020_minilm12.csv')
harmful_at_k_2021 = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_2021_minilm12.csv')
harmful_at_k_2022 = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_2022_minilm12.csv')
harmful_at_k_clef = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_clef_minilm12.csv')
harmful_at_k_clef_v2 = pd.read_csv(f'harmful_at_k/harmful_at_{str(k)}_clef_v2_minilm12.csv')


harmfuls_at_k = {"2020": harmful_at_k_2020, "2021": harmful_at_k_2021, "2022": harmful_at_k_2022, "clef": harmful_at_k_clef, "clef_v2": harmful_at_k_clef_v2}

In [126]:
harmful_at_k_2020

    topic  harmful_at_10
0       1            0.0
1       2            0.1
2       4            0.0
3       6            0.1
4       7            0.0
5       8            0.0
6       9            0.0
7      10            0.0
8      13            0.0
9      14            0.1
10     15            0.0
11     16            0.0
12     17            0.1
13     18            0.0
14     19            0.2
15     20            0.1
16     22            0.1
17     25            0.7
18     27            0.1
19     28            0.0
20     30            0.0
21     31            0.0
22     38            0.1
23     39            0.0
24     40            0.1
25     41            0.0
26     43            0.0
27     44            0.2
28     45            0.1
29     47            0.0
30     49            0.1
31     50            0.1

In [127]:
if metric != "var":
    harmfuls_at_k[corpus][f"{metric}"] = df[f"{metric}"]
else:
    for i in range(1, 4):
        harmfuls_at_k[corpus][f"sigma_{i}"] = df[f"sigma_{i}"]


harmfuls_at_k[corpus]

    topic  harmful_at_10     sigma_1    sigma_2    sigma_3
0     151            0.0  116.101817  19.350303  35.501125
1     152            0.0   49.981538  24.990769  43.825776
2     153            0.5   47.679410  15.893137  23.780222
3     154            0.2   68.992798  22.997599  29.555744
4     155            0.6   62.268474  31.134237  34.403428
5     156            0.1   49.265697  16.421899  39.118725
6     157            0.0   23.072107  11.536054  11.787952
7     158            0.1   24.312253  12.156127  23.753450
8     159            0.8   61.565769  20.521923  40.403816
9     160            0.0    0.000000   0.000000   0.000000
10    161            0.1  147.981568  36.995392  62.444269
11    162            0.0   32.850402  16.425201  32.850402
12    163            0.1   63.793434  21.264478  39.530503
13    164            0.3   73.632597  18.408149  29.600375
14    167            0.2    1.328363   0.664181   1.328363
15    168            0.1  180.678189  22.584774  60.580046
16    170            0.5  170.887078  34.177416  57.826924
17    173            0.4   22.587883  11.293941  18.498431
18    175            0.0   27.426438  13.713219  17.971299
19    177            0.1   79.540972  26.513657  40.072401
20    178            0.0   93.479141  31.159714  54.099785
21    179            0.4   95.009135  31.669712  35.905929
22    181            0.0   17.291357   5.763786   9.834555
23    183            0.0  138.252059  46.084020  52.728486
24    184            0.3   81.778000  40.889000  69.275999
25    185            0.0   19.999611   9.999806  13.084075
26    186            0.0  101.082571  33.694190  43.775979
27    187            0.1   98.635191  32.878397  42.140372
28    188            0.0  145.403339  36.350835  48.164995
29    189            0.4  140.165858  35.041465  62.370271
30    190            0.1   23.426462  11.713231  16.794487
31    192            0.2   80.597630  26.865877  47.114516
32    193            0.0   60.506152  20.168717  41.565600
33    194            0.0   59.031597  11.806319  25.766180
34    195            0.0   82.207983  20.551996  51.243732
35    197            0.1  155.949402  38.987350  71.213249
36    199            0.0   86.862357  21.715589  42.908058

In [128]:
harmfuls_at_k[corpus].corr(method="pearson").round(3)

               topic  harmful_at_10  sigma_1  sigma_2  sigma_3
topic          1.000         -0.276    0.248    0.274    0.297
harmful_at_10 -0.276          1.000    0.083    0.156    0.106
sigma_1        0.248          0.083    1.000    0.809    0.853
sigma_2        0.274          0.156    0.809    1.000    0.875
sigma_3        0.297          0.106    0.853    0.875    1.000

In [129]:
harmfuls_at_k[corpus].corr(method="kendall").round(3)

               topic  harmful_at_10  sigma_1  sigma_2  sigma_3
topic          1.000         -0.176    0.186    0.174    0.207
harmful_at_10 -0.176          1.000    0.086    0.145    0.073
sigma_1        0.186          0.086    1.000    0.748    0.715
sigma_2        0.174          0.145    0.748    1.000    0.745
sigma_3        0.207          0.073    0.715    0.745    1.000

In [130]:
harmfuls_at_k[corpus].corr(method="spearman").round(3)

               topic  harmful_at_10  sigma_1  sigma_2  sigma_3
topic          1.000         -0.236    0.280    0.251    0.335
harmful_at_10 -0.236          1.000    0.116    0.192    0.099
sigma_1        0.280          0.116    1.000    0.873    0.872
sigma_2        0.251          0.192    0.873    1.000    0.889
sigma_3        0.335          0.099    0.872    0.889    1.000